# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21c83e1dcfa4002cf5b69b5df24e6d98352de0aaf647d7ea05fadfee96a8c8722cffb1b4e0ae45d8b5c37a90c06addd6d787e4d367fc1ff49700eddecd54a813

test:
  secret_key_base: c7207bc7e2e5a796b3226b86039e826699c37daae5d192e3023e20936bdbfb838ea6b509f59e6c9db6d43e46e7be5d5157f02caf63081f147b3ef563c52ee1a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 6cc859a4caee5ce0ec7871c01b12fb4b1ccaf0df0c1d35a47ae97eac2f600eafcbca90925db4f312e56eb40ab721c150fd8d8ce460111c6babdce7c76079d405 

#<%= ENV["SECRET_KEY_BASE"] %>
